### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by semcelik** [semcelik/blockchain-example-react-app#1]
- [x] Add redux
- [x] Take transaction from input
- [x] Add saga
- [x] Add loading while mining
- [x] Add Spring Framework and DB for blocks
- [x] Single page app
- [ ] Learn and Configure webpack right way
- [ ] Configure maven dependencies
- [x] Detach Rest Controller and Service Layer
- [ ] Log errors 
- [ ] Add swagger for rest
- [ ] todoları issuelara ayır
- [ ] Add sass for css

--------------------------------
minor things
- [ ] Add Github Pages
- [ ] Add ESLint

**Comment by semcelik** [comment]
test

**Comment by kerematam** [comment]
test v2 xx
